# Generated by Django 5.1.6 on 2025-05-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paymeny_method',
            new_name='payment_method',
        ),
    ]
